DROP TABLE IF EXISTS affirmations;
DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS activities;
DROP TABLE IF EXISTS relaxations;
DROP TABLE IF EXISTS foods;

CREATE TABLE affirmations (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  quote VARCHAR(512) NOT NULL
);

CREATE TABLE favorites (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username VARCHAR(512) NOT NULL,
  favorite_quote VARCHAR(512) NOT NULL
);

CREATE TABLE activities (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  exercise VARCHAR(512) NOT NULL,
  daily_duration VARCHAR(512) NOT NULL
);

CREATE TABLE relaxations (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  technique VARCHAR(512) NOT NULL,
  timing VARCHAR(512) NOT NULL
);

CREATE TABLE foods (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  plant VARCHAR(512) NOT NULL,
  meal VARCHAR(512) NOT NULL
);
